### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by wonderingwombat** [Serene-Arc/bulk-downloader-for-reddit#29]
When I run the script I get the following error for the majority of the entries when running the following command: 

Error:
**<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>**

Command: 
**py -3 script.py .\\NEW_FOLDER\\ANOTHER_FOLDER --saved --limit 1000**

I was able to authenticate Imgur and Reddit successfully.

**Comment by wonderingwombat** [comment]
Just want to confirm that what you want is the output provided in the console? like this: 

**py -3 script.py .\NEW_FOLDER\ANOTHER_FOLDER --saved --limit 1000 > log.txt** 

Is there anyway to do this without sharing all my saved reddit links?

**Comment by aliparlakci** [comment]
I mean the file inside .\NEW_FOLDER\ANOTHER_FOLDER inside folder time stamped in its name. There is a file called CONSOLE_LOG.txt

Check if you get that error when running other commands, in other program modes such as downloading hot posts of r/pics. If you do, share the log with me so that you won't give me your saved reddit links.

**Comment by wonderingwombat** [comment]
I get the same issue with this command: 

**python3 script.py TEST --sort new --time all --limit 10 --link "https://www.reddit.com/r/gifs/search?q=dogs&restrict_sr=on&type=link&sort=new&t=month"**

Imgur is not banned here. 

I've attached the log file. 
[CONSOLE_LOG.txt](https://github.com/aliparlakci/bulk-downloader-for-reddit/files/2178500/CONSOLE_LOG.txt)

**Comment by aliparlakci** [comment]
It looks like your issue is local. It might be caused by Python, Windows or Firewall. Can you try it with a VPN? Those programs get all the permissions from the operating system.
