### ISSUE TITLE
[IMPROVEMENT] Option 'search-existing' scans too many files

### ISSUE THREAD

**Issue by thomas694** [Serene-Arc/bulk-downloader-for-reddit#770]
- [x] I am requesting an improvement.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)

## Description

It's unnecessary to scan the meta files (json/xml/yaml) and compute their hashes as these hashes aren't used anyway.
Skipping these file types by default would save some resources while scanning the files.

Not sure, if it should be labeled bug (or feature), at least an improvement of something that's already there.

**Comment by Serene-Arc** [comment]
The use of this option is highly discouraged. It is inefficient regardless and there are third party tools that perform the same function much better. No work to make it easier to use will be done because it is a deprecated feature. I just can't get rid of it without a major version change.
