### ISSUE TITLE
same folder, separate it by subreddits

### ISSUE THREAD

**Issue by Root-FTW** [Serene-Arc/bulk-downloader-for-reddit#777]
Is there a way to get everything downloaded to the same folder? and don't separate it by subreddits?

![image](https://user-images.githubusercontent.com/108767514/218607799-a0a1d377-6ecb-4a53-a722-ab4b423861a3.png)

**Comment by Serene-Arc** [comment]
This is not the right place to ask questions. Please don't open bug reports to ask questions about the interface.

**Comment by Root-FTW** [comment]
> This is not the right place to ask questions. Please don't open bug reports to ask questions about the interface.

I'm in hundreds of projects on github and this is the only one in all of github where I see the same person respond rudely to everyone who makes a ticket.

It seems that you hate this project, if so I recommend that someone else answer, they always answer rudely.

I also recommend making a discord where the entire community that uses this project can communicate and resolve doubts among ourselves and we don't have to depend on someone who hates the project and responds rudely.

**Comment by Serene-Arc** [comment]
I am the main maintainer for this project, it's my job to answer tickets. If you think a short message asking you to not open bug tickets to ask questions is rude, I don't know what I'm supposed to do. I think it was quite polite. 

We have a discussion page for a reason, and you quite specifically ignored the template that we have for bug reports. If you had used it, and read the parts linked in said template, it should have been quite clear that this was not the correct medium. Especially since your question is clearly answered in the README, which I assume you found out because you closed the issue.

I'm not sure where or why you think I've been rude, so sorry for that, but attacking me for asking you not to file bug reports for things that are not bugs is unreasonable. If you want to ignore every part of the process, don't get offended when that's pointed out.

**Comment by Root-FTW** [comment]
1.- Opening stickers is free, it is unlimited, and nobody can deny me to open all the tickets of doubts that I have.

2.- Almost at the moment I opened the ticket, I closed it because I found what I was looking for, it was not necessary for you to answer me, since the ticket was already closed and you had already solved the doubt, you only answered to bother me.

3.- Nowhere in the readme does it explicitly say: "to avoid dividing by subreddit folder, do the following", you understand the perfect code and you know how it works but not all of us understand or decipher what you tried to explain in the readme, that's why they exist the tickets.

4.- Just as you think that your way of answering is not rude or rude and should not affect me, my way of asking and answering you as I am doing right now should not bother you at all.

5.- Thanks for the project, sorry if I was the only one who told you what everyone thinks but no one dares to tell you.

6.- You say that you have a page for the community to discuss any doubts they may have at the moment? Nowhere in the readme do I see a section that says "HERE is a page or forum so you can join as a community for this project"

> I am the main maintainer for this project, it's my job to answer tickets. If you think a short message asking you to not open bug tickets to ask questions is rude, I don't know what I'm supposed to do. I think it was quite polite.
> 
> We have a discussion page for a reason, and you quite specifically ignored the template that we have for bug reports. If you had used it, and read the parts linked in said template, it should have been quite clear that this was not the correct medium. Especially since your question is clearly answered in the README, which I assume you found out because you closed the issue.
> 
> I'm not sure where or why you think I've been rude, so sorry for that, but attacking me for asking you not to file bug reports for things that are not bugs is unreasonable. If you want to ignore every part of the process, don't get offended when that's pointed out.

**Comment by Serene-Arc** [comment]
If your defense of opening tickets is that nobody can stop you, do you think that you sound polite? The discussions section is right at the top of the page, and is a feature of all GitHub repositories. 

I am going to lock this conversation now, but in the future, please use the systems as intended. It is cleaner and will help more people going forwards if your question is asked and answered in the discussions, where other people can easily find them.
