### ISSUE TITLE
[FEATURE] Cache hashes

### ISSUE THREAD

**Issue by 8ullyMaguire** [Serene-Arc/bulk-downloader-for-reddit#801]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)

## Description

After downloading a subreddit I downloaded another and it started calculating hashes, it took it quite a while, and after it finished I downloaded another subreddit and it started recalculating the hashes again and it took even longer. Saving the hashes for the files would save a lot of processing time. They could be saved in the configuration folder or in the submission files themselves.

**Comment by Serene-Arc** [comment]
The use of hashes to determine existing files is highly discouraged. This feature is the same as #770 and #772 and won't be implemented

**Comment by 8ullyMaguire** [comment]
So remove the option from the README or mention that is deprecated.

**Comment by Serene-Arc** [comment]
That has been done in the development branch. It will be merged in the next update.
