### ISSUE TITLE
[FEATURE] Add MarkDown as a file format option

### ISSUE THREAD

**Issue by dermalikmann** [Serene-Arc/bulk-downloader-for-reddit#816]
- [x] I am requesting/proposing a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)

## Description

I (as many people that use this awesome piece of code) am quite a data hoarder. I download _a lot_ of reddit content, mostly media. But there are also some subs that I scrape in quite regular intervals, that are text only / mainly text, e.g. r/askreddit or r/talesfromtechsupport.

But as you might expect json, yaml and/or xml are hard to read. So I had the idea that maybe an option to save posts as a simple markdown file may be an alternative to view these posts locally.

The markdown file should not contain all information of the original entry, e.g. the id or the pinned status are irrelevant in this case.

**Comment by Serene-Arc** [comment]
I laid out my reasoning in the PR why I don't think that the linked PR is the best approach to this. The goal of this part of the BDFR is to download post metadata. You removed the fields that you don't have a use for, but your use case is not necessarily universal. I think a script would be a better approach, one that parses the YAML/XML output.

**Comment by dermalikmann** [comment]
As noted in the PR: I see the point. it is (in its current form) out of scope. So.... Buh-bye
