### ISSUE TITLE
command to dl from a specific subreddit but between a certain time intervale? 

### ISSUE THREAD

**Issue by deroverda** [Serene-Arc/bulk-downloader-for-reddit#821]
Hi. Newbie here. Tried searching through active and completed issues but couldn't find any info on this. 
So i want to download videos from a certain subreddit but I only want to download from a start date and an end date. How would my options look like? Could anyone please help?

Thanks in advance.

**Comment by Serene-Arc** [comment]
There is no way to do this currently. We use Reddit's official API, praw, as the underlying engine of the BDFR. We're limited to what praw can do, which is the same as the website, more or less. If you can't select posts between two dates on the website, we can't do it here.

The exception would be to put the post time in the name and then filter all of downloads, deleting whatever you don't want, but that's about it I'm afraid.
