### ISSUE TITLE
[FEATURE] Any way to include pushshift support?

### ISSUE THREAD

**Issue by TomArrow** [Serene-Arc/bulk-downloader-for-reddit#827]
- [x ] I am requesting a feature.
- [ x] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](../../README.md#configuration)

## Description

Would be cool if pushshift could be utilized to:
1. Find very old threads on a subreddit that the normal website doesn't provide and then use normal reddit to scrape them.
2. Get deleted comments/posts.

**Comment by Serene-Arc** [comment]
This isn't really possible. Our code is based around praw, the Reddit API for Python programs. Everything is written in terms of praw, to make the BDFR work for Pushshift it would, in very real terms, mean making a completely different program. Basically everything would have to be gutted and rewritten in the core classes.
