### ISSUE TITLE
Question about /scripts

### ISSUE THREAD

**Issue by Cassian-Andor** [Serene-Arc/bulk-downloader-for-reddit#830]
I see the bash scripts had the output (2nd parameter) removed, may I ask why? It is still available on the batch scripts (ps1) and it's still in the docs (which confused me at first then passing a second parameter but getting stdout)
https://github.com/aliparlakci/bulk-downloader-for-reddit/commit/484bde9b136f18a02d9629b655bb3d9405848719

The docs should be updated to present the differences in usage between bash and batch

**Comment by OMEGARAZER** [comment]
The powershell scripts are updated to match the bash scripts on the dev branch but the readme had not been completely updated along with it.

**Comment by Cassian-Andor** [comment]
Thanks for fix
