### ISSUE TITLE
Completions command in README is incorrect

### ISSUE THREAD

**Issue by mtafiti** [Serene-Arc/bulk-downloader-for-reddit#844]
## Description

The completions command in the main README is either incorrect or has a typo.
## Command

```text
bdfr completions
```

## Environment (please complete the following information)

- OS: All
- Python version: 3.9.x

## Logs

```text
$ bdfr completions
Usage: bdfr [OPTIONS] COMMAND [ARGS]...

Error: No such command 'completions'.
```

Easy fix: either change the command name or readme snippet

**Comment by Serene-Arc** [comment]
What version of the BDFR are you using?

**Comment by mtafiti** [comment]
`You are currently using v2.6.2 the latest is v2.6.2`

**Comment by mtafiti** [comment]
FYI the correct command name is `completion`

**Comment by BluesFanUK** [comment]
> FYI the correct command name is `completion`

Not supported in Windows apparently.
