### ISSUE TITLE
[FEATURE] a way to view or read the output easily

### ISSUE THREAD

**Issue by JunkyardCat** [Serene-Arc/bulk-downloader-for-reddit#856]
- [ ] I am requesting a feature.
- [ ] I am running the latest version of BDfR
- [ ] I have read the [Opening an issue](../../README.md#configuration)

## Description

Clearly state the current situation and issues you experience. Then, explain how this feature would solve these issues and make life easier. Also, explain the feature with as many detail as possible.

Is there a way to view the output in something easy to read? Right now i find it hard to read

**Comment by Serene-Arc** [comment]
Please provide more details. What output? For what feature?

**Comment by JunkyardCat** [comment]
Like if i open the json file in a browser itll output like a thread and not some kind of json. Maybe something like a thing that converts the json file to a html file that lokks like a reddit post

**Comment by Serene-Arc** [comment]
There's [another project](https://github.com/BlipRanger/bdfr-html) for that. If you can't read JSON, why are you trying to save posts with it? What are you trying to do with the bdfr? What goal are you trying to accomplish?

**Comment by JunkyardCat** [comment]
I want to archive the post and its comment then later on be able to view them at ease. I can view and read json on my browser fine but it just takes more brain power thats all. Thanks for the link hopefully it still works
