### ISSUE TITLE
[FEATURE] Add an Option to Create a List that Associates Downloads to their Origin

### ISSUE THREAD

**Issue by TheFrozenDuck** [Serene-Arc/bulk-downloader-for-reddit#903]
- [/] I am requesting a feature.
- [/] I am running the latest version of BDfR
- [/] I have read the [Opening an issue](../../README.md#configuration)

## Description

When downloading media, etc. it sometimes is useful to also have a link at hand that allows to access the post the asset originates from.

I would like to suggest an option that either is

- added to **download** to create a list that is a mapping of file name to post
- or added to **archive** to limit the downloaded data to only a subset, e.g. strip the comments

**Comment by Serene-Arc** [comment]
The post ID serves this purpose. You can use `reddit.com/{post_id}` to go to the post with that ID.
