### ISSUE TITLE
[Question] Should there be duplicate ids in the output file when using extract_successful_ids.ps1?

### ISSUE THREAD

**Issue by JoeyJFranklin** [Serene-Arc/bulk-downloader-for-reddit#920]
Like this (number on the left is line number)

![image](https://github.com/aliparlakci/bulk-downloader-for-reddit/assets/134342419/58574656-e942-46eb-ac9f-6f10c0c1902f)

I'm just curious if it is intentional that there are duplicate id numbers.

**Comment by Serene-Arc** [comment]
It's possible, yes. It scrapes the logs, and the same ID appears in multiple places. Running it through `sort` and then `uniq` is encouraged.
