### ISSUE TITLE
[BUG] The filename_restriction_scheme option is not implemented for YAML files

### ISSUE THREAD

**Issue by ZapperDJ** [Serene-Arc/bulk-downloader-for-reddit#933]
- [x ] I am reporting a bug.
- [x ] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

When using the filename-restriction-scheme option on a YAML file the program doesn't recognize the option

## Command

```text
folder_scheme: "{REDDITOR}/{SUBREDDIT}"
no_dupes: true
sort: new
authenticate: true
log: "bdfr.log"
config: "myconf.cfg"
submitted: true
exclude_id_file: [downloadedids]
filename_restriction_scheme: windows
max_wait_time: 0
user:
  - somerandomuser
```

## Environment (please complete the following information)

- OS: Linux
- Python version: 3.9

## Logs

```text
Ignoring an unknown YAML argument: filename_restriction_scheme
```

**Comment by Serene-Arc** [comment]
That...is strange. Does it still happen when you put 'windows' in quotes? Also are you sure you're using the latest version?

**Comment by ZapperDJ** [comment]
It was my fault, I had twoo different versions of python installed and the one I was using was running an older version of bdfr
