### ISSUE TITLE
[BUG] BDFR downloads nothing

### ISSUE THREAD

**Issue by ghost** [Serene-Arc/bulk-downloader-for-reddit#950]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description
absolutely nothing is downloaded, even when running as administrator

## Command
```text
python -m bdfr clone --user not_telling_you -v ./REDDIT
```

## Environment (please complete the following information)

- OS: Windows 10
- Python version: 3.12.1

## Logs

```text
[2024-03-07 21:47:08,665 - bdfr.connector - DEBUG] - Disabling the following modules:
[2024-03-07 21:47:08,681 - bdfr.connector - DEBUG] - Using unauthenticated Reddit instance
[2024-03-07 21:47:08,681 - root - INFO] - Program complete
```

**Comment by Serene-Arc** [comment]
That user doesn't have any posts. That's why nothing is being downloaded.
