### ISSUE TITLE
[BUG]  bdfr.downloader - ERROR] - Site Youtube failed to download submission

### ISSUE THREAD

**Issue by Root-FTW** [Serene-Arc/bulk-downloader-for-reddit#959]
it has been stopped for 3 hours, before that I had already tried and it stays where it is, I have the ---max-wait-time in 60 seconds, I have tried different times but it is still the same.

![image](https://github.com/aliparlakci/bulk-downloader-for-reddit/assets/108767514/50483195-f680-4aaa-b1c9-1208d8d9d02a)

**Comment by Serene-Arc** [comment]
https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue
