### ISSUE TITLE
[FEATURE] download media based on a list of reddit posts provided

### ISSUE THREAD

**Issue by Laures** [Serene-Arc/bulk-downloader-for-reddit#962]
- [x] I am requesting a feature.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](../../README.md#configuration)

## Description

I tried to find a way to download my upvotes from reddit beyond the last 1k. The api does not work for that (as stated in your documentation) BUT there is indeed a workaround: 

Request all your data from reddit (for example under the GDPR). the post_votes.csv in the resulting archive contains all votes, whether they are up or downvotes, the post ID and a permalink.

I would like a way to use this data to download media from reddit.

**Comment by Laures** [comment]
Here is the format of the post_votes.csv

```
id,permalink,direction
1dzprjk,https://www.reddit.com/r/anime_titties/comments/1dzprjk/frances_new_leftwing_coalition_reveals_plans_to/,up
1dzs1ho,https://www.reddit.com/r/anime_titties/comments/1dzs1ho/zelenskyy_ukraine_needs_128_f16_jets_to_compete/,down
```

**Comment by Serene-Arc** [comment]
What you want to do is take all of those IDs and put them in a text file, then use `--include-id-file` to download them. Open the CSV in Excel and delete the other columns, then delete the first row with the header and it will do what you want.

**Comment by Laures** [comment]
i completely missed this feature. thanks.
