### ISSUE TITLE
When I clone all my saved posts and then some post gets deleted by reddit will the json file be modified with the new info?

### ISSUE THREAD

**Issue by z33a** [Serene-Arc/bulk-downloader-for-reddit#965]
I have set up a service where, every day at midnight, BDFR runs a clone operation on all my saved posts. For example, if I save a post at 3 PM, BDFR runs at midnight and downloads that post, saving its images and a JSON file with its information. The next day the post gets taken down by Reddit or deleted by the original author. Will BDFR, when it runs again at midnight, overwrite the information in the JSON file with the current one?

**Comment by Serene-Arc** [comment]
Yes it will, if you don't skip the post.
