### ISSUE TITLE
[BUG] OSError: File name too long

### ISSUE THREAD

**Issue by eagerm** [Serene-Arc/bulk-downloader-for-reddit#966]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

Some downloads have very long file names.  When checking to see if the file has already been downloaded, this causes stat() to fail, generating an exception, which is not caught.

## Command

```bdfr download /probox/reddit --no-dupes -s <subred>
```

## Environment (please complete the following information)

- OS: Linux
- Python version: 3.12.4

## Logs

Not available

## Patch

downloader.py: 112
```
           try:
                if destination.exists():
                    logger.debug(f"File {destination} from submission {submission.id} already exists, continuing")
                    continue
                elif not self.download_filter.check_resource(res):
                    logger.debug(f"Download filter removed {submission.id} file with URL {submission.url}")
                    continue
            except OSError as e:
                logger.error(
                    f"Failed existence check {submission.id}: {e}")
                continue
```

**Comment by Serene-Arc** [comment]
Hi, is there a reason you haven't added logs?

**Comment by eagerm** [comment]
I didn't capture logs for the failing case.

**Comment by Serene-Arc** [comment]
There will always be logs. The BDFR writes them to a file in your configuration directory.

**Comment by eagerm** [comment]
I fixed the failure before I looked at the bug reporting process which requested logs.  I did not go back and remove the fix and rerun the failing execution.

**Comment by Serene-Arc** [comment]
It's more complicated than that. We have code already that is supposed to detect the file system and then truncate the file names according to the system limits. If it's failing here, there's a deeper reason than your patch. If files are being written in a manner that causes them to later fail when being read, that's a problem. 

Can you provide more details on your setup? Are you using any kind of network share? Windows or Linux?

**Comment by eagerm** [comment]
Fedora 40 Linux, local file system.

I'll back out my fix and see if I can reproduce the problem.

**Comment by eagerm** [comment]
[log_output.txt](https://github.com/user-attachments/files/16741898/log_output.txt)
